var myChart4 = echarts.init(document.getElementById('data4'));
const list = [
  {value: '50',name: '特种兵式旅游',},
  { value: '30', name: '反向旅游' },
  { value: '29', name: '避暑' },
  { value: '28', name: '“进淄赶考”' },
  { value: '27', name: '打卡旅游' },
  { value: '26', name: '美食游' },
  { value: '25', name: '围炉煮茶' },
  { value: '24', name: '仪式游' },
  { value: '23', name: 'Citywalk' },
  { value: '22', name: '研学旅游' },
  { value: '21', name: '康养旅游' },
  { value: '20', name: '自驾出游' },
  { value: '16', name: '45度躺平' },
  { value: '15', name: '旅居结合' },
  { value: '14', name: '避冷' },
  { value: '13', name: '村超BA' },
  { value: '12', name: '沉浸式' },
];
var data4Data = {
  '全国': [
    { value: '50', name: '特种兵式旅游' },
    { value: '30', name: '反向旅游' },
    { value: '29', name: '避暑' },
    { value: '28', name: '“进淄赶考”' },
    { value: '27', name: '打卡旅游' },
    { value: '26', name: '美食游' },
    { value: '25', name: '围炉煮茶' },
    { value: '24', name: '仪式游' },
    { value: '23', name: 'Citywalk' },
    { value: '22', name: '研学旅游' },
    { value: '21', name: '康养旅游' },
    { value: '20', name: '自驾出游' },
    { value: '16', name: '45度躺平' },
    { value: '15', name: '旅居结合' },
    { value: '14', name: '避冷' },
    { value: '13', name: '村超BA' },
    { value: '12', name: '沉浸式' },
  ],
  '北京': [
    {value: '49.5', name: '故宫博物院'},
    {value: '42', name: '圆明园'},
    {value: '50', name: '环球影城'},
    {value: '38.5', name: '王府井'},
    {value: '44.5', name: '恭王府'},
    {value: '36', name: '天安门广场'},
    {value: '46.5', name: '八达岭长城'},
    {value: '44.5', name: '天坛'},
    {value: '36', name: '香山公园'},
    {value: '37', name: '北海公园'},
    {value: '30', name: '北京烤鸭'},
    {value: '45', name: '颐和园'},
    {value: '39', name: '明十三陵'},
    {value: '45', name: '中国国家博物馆'},
    {value: '39.5', name: '鸟巢'},
    {value: '34', name: '清华大学'},
    // ...
  ],
  '四川': [
    {value: '44.5', name: '三星堆'},
    {value: '45', name: '峨眉山'},
    {value: '43.5', name: '乐山大佛'},
    {value: '34', name: '太古里'},
    {value: '48.5', name: '大熊猫'},
    {value: '30', name: '理塘'},
    {value: '46.5', name: '都江堰'},
    {value: '44.5', name: '杜甫草堂'},
    {value: '28', name: '天府广场'},
    {value: '45.5', name: '武侯祠'},
    {value: '46.5', name: '九寨沟'},
    {value: '30', name: '钵钵鸡'},
    {value: '30', name: '凉粉'},
    {value: '30', name: '火锅'},
    {value: '34', name: '阆中古城'},
    {value: '38', name: '邓小平故里'},
    // ...
  ],
  '海南': [
    {value: '30', name: '西沙群岛'},
    {value: '36', name: '三亚湾'},
    {value: '32', name: '文昌卫星发射中心'},
    {value: '42', name: '鹿回头'},
    {value: '35', name: '博鳌'},
    {value: '41', name: '亚龙湾'},
    {value: '43.5', name: '天涯海角'},
    {value: '22', name: '国际免税城'},
    {value: '48', name: '蜈支洲岛'},
    {value: '30', name: '文昌鸡'},
    {value: '45', name: '南山'},
    // ...
  ],
  '河北': [
    {value: '35', name: '阿那亚礼堂'},
    {value: '35.5', name: '北戴河'},
    {value: '40.5', name: '避暑山庄'},
    {value: '31', name: '万龙滑雪场'},
    {value: '37.5', name: '山海关'},
    {value: '37', name: '鸽子窝公园'},
    {value: '30', name: '驴肉火烧'},
    {value: '35', name: '正定古城'},
    {value: '35.5', name: '秦皇岛野生动物园'},
    {value: '30', name: '正宗安徽牛肉板面'},
    // ...
  ],
  '云南': [
    {value: '44.5', name: '大理'},
    {value: '37.5', name: '香格里拉'},
    {value: '42.5', name: '丽江'},
    {value: '44', name: '石林'},
    {value: '37.5', name: '昆明动物园'},
    {value: '41.5', name: '西双版纳'},
    {value: '23.5', name: '飞来寺'},
    {value: '46', name: '玉龙雪山'},
    {value: '30', name: '澜沧江'},
    {value: '38.5', name: '松赞林寺'},
    {value: '44.5', name: '曼听公园'},
    {value: '43.5', name: '滇池'},
    {value: '42', name: '洱海'},
    {value: '40', name: '泼水节'},
    // ...
  ],
  '广东': [
    {value: '43', name: '广州塔'},
    {value: '34.5', name: '丹霞山'},
    {value: '35.5', name: '白云山'},
    {value: '31.5', name: '深圳湾'},
    {value: '30', name: '红树林'},
    {value: '39.5', name: '欢乐谷'},
    {value: '42.5', name: '世界之窗'},
    {value: '46', name: '长隆度假区'},
    {value: '38.5', name: '华侨城'},
    {value: '34.5', name: '南越王博物院'},
    {value: '32', name: '景山公园'},
    {value: '31', name: '古龙峡'},
    {value: '30', name: '白切鸡'},
    {value: '30', name: '肠粉'},
    // ...
  ],
  '广西': [
    {value: '42.5', name: '漓江'},
    {value: '45.5', name: '涠洲岛'},
    {value: '43', name: '遇龙河'},
    {value: '41.5', name: '青秀山'},
    {value: '41.5', name: '龙脊梯田'},
    {value: '37.5', name: '程阳八寨'},
    {value: '38', name: '阳朔西街'},
    {value: '43.5', name: '德天瀑布'},
    {value: '38', name: '北海银滩'},
    {value: '30', name: '螺狮粉'},
    {value: '30', name: '桂林米粉'},
    {value: '42.5', name: '象鼻山'},
    // ...
  ],
  '山西': [
    {value: '46', name: '华山'},
    {value: '42.5', name: '平遥古城'},
    {value: '41.5', name: '云冈石窟'},
    {value: '41', name: '壶口瀑布'},
    {value: '40', name: '悬空寺'},
    {value: '38', name: '太行山大峡谷'},
    {value: '34.5', name: '方特欢乐世界'},
    {value: '37', name: '华严寺'},
    {value: '38', name: '雁门关'},
    {value: '40', name: '五台山'},
    {value: '30', name: '刀削面'},
    {value: '30', name: '平遥牛肉'},
    {value: '39.5', name: '乔家大院'},
    {value: '34.5', name: '鹳雀楼'},
    // ...
  ],
  '辽宁': [
    {value: '42.5', name: '沈阳故宫'},
    {value: '41.5', name: '张学良故居'},
    {value: '40', name: '方特欢乐世界'},
    {value: '31.5', name: '北陵公园'},
    {value: '29.5', name: '北普陀山'},
    {value: '30', name: '九一八历史博物馆'},
    {value: '32.5', name: '丹东凤凰山'},
    {value: '37', name: '棒棰岛'},
    {value: '41', name: '老虎滩海洋公园'},
    {value: '37', name: '沈阳博物馆'},
    {value: '36', name: '本溪水洞'},
    // ...
  ],
  '吉林': [
    {value: '34', name: '万科松花湖度假区'},
    {value: '29.5', name: '雾凇岛'},
    {value: '26.5', name: '松花江'},
    {value: '26', name: '北山公园'},
    {value: '25', name: '吉林省博物馆'},
    {value: '41.5', name: '长白山'},
    {value: '38.5', name: '净月潭'},
    {value: '38.5', name: '伪满皇宫博物院'},
    {value: '36', name: '长影世纪城'},
    {value: '33.5', name: '魔界风景区'},
    {value: '31.5', name: '吉林省东北虎园'},
    // ...
  ],
  '黑龙江': [
    {value: '46', name: '哈尔滨冰雪大世界'},
    {value: '41', name: '东北虎林园'},
    {value: '40', name: '圣索菲亚大教堂'},
    {value: '39.5', name: '哈尔滨极地公园'},
    {value: '39', name: '伏尔加庄园'},
    {value: '37.5', name: '北极村'},
    {value: '38.5', name: '中央大街'},
    {value: '37.5', name: '太阳岛风景区'},
    {value: '36.5', name: '中国雪乡'},
    {value: '35.5', name: '扎龙生态旅游区'},
    {value: '29', name: '黑龙江省博物馆'},
    // ...
  ],
  '江苏': [
    {value: '44.5', name: '拙政园'},
    {value: '43.5', name: '牛首山'},
    {value: '42.5', name: '寒山寺'},
    {value: '42', name: '瘦西湖'},
    {value: '41', name: '周庄'},
    {value: '40.5', name: '鼋头渚'},
    {value: '40.5', name: '夫子庙'},
    {value: '40.5', name: '狮子林'},
    {value: '40', name: '虎丘山'},
    {value: '39.5', name: '留园'},
    {value: '39.5', name: '南京博物馆'},
    {value: '39.5', name: '明孝陵'},
    {value: '39', name: '同里古镇'},
    {value: '38.5', name: '钟山'},
    {value: '38.5', name: '连岛'},
    {value: '38', name: '个园'},
    {value: '36', name: '瞻园'},
    {value: '35.5', name: '玄武湖'},
    {value: '30', name: '松鼠桂鱼'},
    {value: '30', name: '咸水鸭'},
    {value: '34.5', name: '鸡鸣寺'},
    // ...
  ],
  '浙江': [
    {value: '44.5', name: '灵隐寺'},
    {value: '43.5', name: '乌镇'},
    {value: '43', name: '西湖'},
    {value: '43', name: '普陀山'},
    {value: '43', name: '杭州宋城'},
    {value: '41.5', name: '横店影视城'},
    {value: '41', name: '西溪国家湿地公园'},
    {value: '40.5', name: '莫干山'},
    {value: '40', name: '千岛湖'},
    {value: '39.5', name: '雁荡山'},
    {value: '37.5', name: '钱塘江'},
    {value: '37', name: '西塘'},
    {value: '36', name: '绍兴古城'},
    {value: '35', name: '岳王庙'},
    {value: '33.5', name: '兰亭'},
    {value: '38', name: '朱家尖'},
    {value: '38', name: '神仙居'},
    // ...
  ],
  '安徽': [
    {value: '45', name: '黄山'},
    {value: '42.5', name: '宏村'},
    {value: '40.5', name: '九华山'},
    {value: '38.5', name: '西递'},
    {value: '37', name: '三河古镇'},
    {value: '46', name: '徽州古城'},
    {value: '35.5', name: '天堂寨'},
    {value: '35.5', name: '天柱山'},
    {value: '35.5', name: '呈坎'},
    {value: '35', name: '李鸿章故居'},
    {value: '34.5', name: '齐云山'},
    {value: '32', name: '琅琊山'},
    // ...
  ],
  '福建': [
    {value: '45.5', name: '鼓浪屿'},
    {value: '43.5', name: '厦门园林植物园'},
    {value: '42', name: '平潭岛'},
    {value: '41.5', name: '武夷山'},
    {value: '40.5', name: '厦门大学'},
    {value: '39.5', name: '云水谣'},
    {value: '39', name: '福建土楼'},
    {value: '38', name: '南普陀寺'},
    {value: '38', name: '曾厝安'},
    {value: '36', name: '双子塔'},
    {value: '38', name: '清源山'},
    {value: '37.5', name: '太姥山'},
    {value: '37.5', name: '湄洲岛'},
    {value: '31', name: '金门'},
    {value: '32.5', name: '白水洋'},
    // ...
  ],
  '江西': [
    {value: '44', name: '婺源篁岭'},
    {value: '43.5', name: '望仙谷'},
    {value: '43', name: '滕王阁'},
    {value: '42', name: '庐山'},
    {value: '41.5', name: '三清山'},
    {value: '40.5', name: '武功山'},
    {value: '39.5', name: '婺女洲'},
    {value: '37', name: '海昏侯国遗址公园'},
    {value: '37', name: '龙虎山'},
    {value: '34', name: '井冈山'},
    {value: '37.5', name: '景德陶瓷'},
    {value: '35', name: '鄱阳湖'},
    // ...
  ],
  '山东': [
    {value: '44', name: '趵突泉'},
    {value: '42', name: '刘公岛'},
    {value: '42', name: '崂山'},
    {value: '41.5', name: '泰山'},
    {value: '41', name: '莲花阁'},
    {value: '38', name: '台儿庄古城'},
    {value: '40', name: '阜明故城'},
    {value: '38', name: '大明湖'},
    {value: '35.5', name: '八仙过海'},
    {value: '35.5', name: '孔庙'},
    {value: '33.5', name: '岱庙'},
    {value: '33.5', name: '青州古城'},
    {value: '33', name: '沂蒙山'},
    {value: '48', name: '淄博烧烤'},
    // ...
  ],
  '河南': [
    {value: '44.5', name: '龙门石窟'},
    {value: '42.5', name: '老君山'},
    {value: '41', name: '清明上河园'},
    {value: '40', name: '少林寺'},
    {value: '38.5', name: '洛邑古城'},
    {value: '38.5', name: '云台山'},
    {value: '38', name: '白马寺'},
    {value: '38', name: '开封府'},
    {value: '36.5', name: '殷墟'},
    {value: '34.5', name: '大相国寺'},
    {value: '33.5', name: '太行山'},
    {value: '34.5', name: '嵩山'},
    {value: '30', name: '烩面'},
    {value: '30', name: '胡辣汤'},
    {value: '33', name: '胖东来'},
    {value: '38', name: '洛阳博物馆'},
    // ...
  ],
  '湖北': [
    {value: '45.5', name: '黄鹤楼'},
    {value: '40.5', name: '武当山'},
    {value: '41', name: '恩施大峡谷'},
    {value: '41', name: '湖北省博物馆'},
    {value: '40.5', name: '汉口江滩'},
    {value: '39', name: '武大樱花'},
    {value: '40', name: '神农架'},
    {value: '39.5', name: '东湖'},
    {value: '39', name: '三峡大坝'},
    {value: '36', name: '襄阳古城'},
    {value: '34.5', name: '古隆中'},
    {value: '33.5', name: '荆州古城'},
    {value: '37', name: '清江画廊'},
    {value: '36', name: '赤壁'},
    {value: '34', name: '天堂寨'},
    {value: '32', name: '张居正故居'},
    {value: '30', name: '热干面'},
    {value: '30', name: '武昌鱼'},
    {value: '33', name: '长江大桥'},
    // ...
  ],
  '湖南': [
    {value: '46.5', name: '张家界'},
    {value: '45', name: '橘子洲'},
    {value: '44.5', name: '湖南博物院'},
    {value: '41', name: '湖南省博物馆'},
    {value: '42.5', name: '杜甫江阁'},
    {value: '42', name: '凤凰古城'},
    {value: '41', name: '岳麓山'},
    {value: '41', name: '芙蓉镇'},
    {value: '40.5', name: '岳阳楼'},
    {value: '39.5', name: '南岳衡山'},
    {value: '39.5', name: '岳麓书院'},
    {value: '36', name: '桃花源'},
    {value: '35', name: '崀山'},
    {value: '39.5', name: '韶山'},
    {value: '32', name: '洞庭湖'},
    {value: '31.5', name: '湘江'},
    {value: '46.5', name: '天门山'},
    {value: '32', name: '臭豆腐'},
    // ...
  ],
  '贵州': [
    {value: '46', name: '黄果树瀑布'},
    {value: '44.5', name: '西江千户苗寨'},
    {value: '44', name: '梵净山'},
    {value: '41', name: '湖南省博物馆'},
    {value: '45', name: '荔波小七孔'},
    {value: '42.5', name: '青岩古镇'},
    {value: '41', name: '肇兴侗寨'},
    {value: '40', name: '织金洞'},
    {value: '39.5', name: '黔灵山'},
    {value: '38.5', name: '中国天眼'},
    {value: '37.5', name: '乌江寨'},
    {value: '37.5', name: '乌蒙大草原'},
    {value: '36.5', name: '赤水丹霞'},
    {value: '35.5', name: '铜仁大峡谷'},
    {value: '30', name: '遵义古城'},
    {value: '32.5', name: '茅台镇'},
    {value: '38', name: '万峰林'},
    // ...
  ],
  '陕西': [
    {value: '49', name: '秦始皇陵兵马俑'},
    {value: '46.5', name: '西安城墙'},
    {value: '46', name: '华山'},
    {value: '46', name: '华清宫'},
    {value: '43', name: '西安钟楼'},
    {value: '43.5', name: '陕西历史博物馆'},
    {value: '42.5', name: '大雁塔'},
    {value: '42', name: '大唐不夜城'},
    {value: '41', name: '大明宫国家遗址公园'},
    {value: '38', name: '秦岭野生动物园'},
    {value: '36', name: '黄帝陵'},
    {value: '36', name: '乾陵'},
    {value: '34', name: '宝塔山'},
    {value: '34', name: '骊山'},
    {value: '30', name: '肉夹馍'},
    {value: '30', name: 'biangbiang面'},
    {value: '30', name: '油泼面'},
    // ...
  ],
  '甘肃': [
    {value: '43.5', name: '鸣沙山月牙泉'},
    {value: '43', name: '张掖七彩丹霞旅游景区'},
    {value: '42', name: '莫高窟'},
    {value: '41', name: '嘉峪关关城'},
    {value: '34.5', name: '甘肃省博物馆'},
    {value: '43.5', name: '陕西历史博物馆'},
    {value: '38', name: '麦积山石窟'},
    {value: '35.5', name: '大佛寺'},
    {value: '35', name: '玉门关'},
    {value: '38', name: '秦岭野生动物园'},
    {value: '34.5', name: '兰州老街'},
    {value: '33.5', name: '崆峒山'},
    {value: '33.5', name: '伏羲庙'},
    {value: '30.5', name: '金塔胡杨林'},
    {value: '31', name: '祁连山'},
    {value: '38.5', name: '扎尕那'},
    {value: '36.5', name: '平山湖大峡谷'},
    {value: '30', name: '兰州牛肉面'},
    // ...
  ],
  '青海': [
    {value: '43', name: '茶卡盐湖'},
    {value: '41.5', name: '塔尔寺'},
    {value: '41.5', name: '青海湖'},
    {value: '39', name: '乌素特水上雅丹地质公园'},
    {value: '38', name: '察尔汗盐湖'},
    {value: '36.5', name: '西宁野生动物园'},
    {value: '36', name: '日月山'},
    {value: '32', name: '柴达木盆地'},
    {value: '36', name: '卓尔山'},
    {value: '32', name: '龙羊峡'},
    {value: '32', name: '青海省博物馆'},
    {value: '29.5', name: '雅丹魔鬼城'},
    // ...
  ],
  '台湾': [
    {value: '37.5', name: '台北故宫博物馆'},
    {value: '35.5', name: '日月潭'},
    {value: '35.5', name: '台北101大楼'},
    {value: '31', name: '野柳地质公园'},
    {value: '31.5', name: '士林夜市'},
    {value: '36.5', name: '台北市立动物园'},
    {value: '32', name: '阿里山'},
    {value: '30', name: '艋舺龙山寺'},
    // ...
  ],
  '内蒙古': [
    {value: '41.5', name: '大召寺'},
    {value: '40.5', name: '响沙湾'},
    {value: '39', name: '呼伦贝尔大草原'},
    {value: '39', name: '乌兰布统'},
    {value: '38.5', name: '阿尔山国家森林公园'},
    {value: '38.5', name: '辉腾锡勒草原'},
    {value: '38', name: '满洲里国门'},
    {value: '36', name: '额济纳胡杨林'}, 
    {value: '35', name: '内蒙古博物院'},
    {value: '35', name: '额尔古纳湿地'},
    {value: '35', name: '成吉思汗陵'},
    {value: '35', name: '五当召'},
    {value: '34.5', name: '玉龙沙湖'},
    {value: '34', name: '鄂尔多斯草原'},
    {value: '33.5', name: '白桦林'},
    {value: '33.5', name: '呼伦湖'},
    {value: '30', name: '烤全羊'},
    {value: '28', name: '摔跤'},
    {value: '28', name: '蒙古包'},
    // ...
  ],
  '西藏': [
    {value: '44.5', name: '布达拉宫'},
    {value: '40', name: '纳木措'},
    {value: '38.5', name: '大昭寺'},
    {value: '38.5', name: '八廓街'},
    {value: '38', name: '巴松措'},
    {value: '38', name: '雅鲁藏布大峡谷'},
    {value: '37', name: '羊卓雍错'},
    {value: '35.5', name: '南迦巴瓦峰'},
    {value: '34.5', name: '奇林峡'},
    {value: '35', name: '珠穆朗玛峰'},    
    {value: '33', name: '扎什伦布寺'},
    {value: '32.5', name: '罗布林卡'},
    {value: '32.5', name: '西藏博物馆'},
    {value: '31.5', name: '冈仁波齐'},
    {value: '30.5', name: '然乌湖'},
    {value: '34.5', name: '来古冰川'},
    {value: '31', name: '卡若拉冰川'},
    {value: '30', name: '酥油茶'},
    {value: '30', name: '糌粑'},
    // ...
  ],
  '宁夏': [
    {value: '41', name: '沙坡头'},
    {value: '39.5', name: '镇北堡西部影城'},
    {value: '37', name: '西夏陵'},
    {value: '35.5', name: '贺兰山'},
    {value: '33', name: '青铜峡黄河大峡谷'},
    {value: '32.5', name: '宁夏博物馆'},
    {value: '32', name: '六盘山'},
    {value: '32', name: '鸣翠湖'},
    {value: '31.5', name: '腾格里沙漠'},
    {value: '31', name: '须弥山石窟'},    
    {value: '32', name: '黄沙古渡原'},
    {value: '34', name: '沙湖'},
    {value: '37', name: '水洞沟'},
    {value: '30', name: '烩羊杂碎'},
    // ...
  ],
  '新疆': [
    {value: '43.5', name: '赛里木湖'},
    {value: '42.5', name: '喀纳斯'},
    {value: '42', name: '天山天池'},
    {value: '41', name: '乔木'},
    {value: '39', name: '世界魔鬼城'},
    {value: '39', name: '新疆维吾尔自治区博物馆'},
    {value: '38.5', name: '新疆国际大巴扎'},
    {value: '38', name: '可可托海'},
    {value: '37.5', name: '五彩滩'},
    {value: '46', name: '巴音布鲁克'},    
    {value: '36.5', name: '那拉提'},
    {value: '32.5', name: '博斯腾湖'},
    {value: '36.5', name: '火焰山'},
    {value: '36', name: '库木塔格沙漠'},
    {value: '36', name: '喀什古城'},
    {value: '33.5', name: '独库公路'},
    {value: '33.5', name: '帕米尔高原'},
    {value: '32', name: '楼兰古城'},
    {value: '30.5', name: '盘龙古道'},
    {value: '30', name: '大盘鸡'},
    {value: '30', name: '羊肉串'},
    // ...
  ],
  '天津': [
    {value: '38', name: '天津之眼摩天轮'},
    {value: '36.5', name: '海河游船'},
    {value: '33.5', name: '静园'},
    {value: '31.5', name: '盘山'},
    {value: '31', name: '相声'},
    // ...
  ],
  '上海': [
    {value: '49.5', name: '迪士尼'},
    {value: '45', name: '东方明珠'},
    {value: '45', name: '陆家嘴'},
    {value: '44', name: '外滩'},
    {value: '42', name: '豫园'},
    {value: '39', name: '南京路'},
    {value: '34', name: '黄河路'},
    {value: '38.5', name: '黄浦江'},
    {value: '36.5', name: '城隍庙'},
    {value: '38.5', name: '上海科技馆'},
    {value: '32', name: '排骨年糕'},
    // ...
  ],
  '重庆': [
    {value: '43.5', name: '长江索道'},
    {value: '42.5', name: '武隆天生三桥'},
    {value: '42.5', name: '武隆喀斯特旅游区'},
    {value: '40.5', name: '洪崖洞民俗风貌区'},
    {value: '40.5', name: '磁器口古镇'},
    {value: '40', name: '重庆动物园'},
    {value: '39.5', name: '解放路步行街'},
    {value: '39', name: '仙女山国家森林公园'},
    {value: '38', name: '大足石刻'},
    {value: '38', name: '白帝城'},
    {value: '38', name: '湖广会馆'},
    {value: '35.5', name: '朝天门广场'},
    {value: '34', name: '白公馆'},
    {value: '33.5', name: '渣滓洞'},
    {value: '32', name: '火锅'},
    // ...
  ],
  '香港': [
    {value: '50', name: '迪士尼乐园'},
    {value: '45.5', name: '香港海洋公园'},
    {value: '44.5', name: '太平山顶'},
    {value: '42.5', name: '尖沙咀'},
    {value: '42.5', name: '香港故宫文化博物馆'},
    {value: '42', name: '昂坪360'},
    {value: '42', name: '大屿山'},
    {value: '41', name: '维多利亚港'},
    {value: '39', name: '中环'},
    {value: '31', name: '金紫荆广场'},
    {value: '30', name: '天坛大佛'},
    {value: '30', name: '重庆大厦'},
    {value: '32', name: '庙街'},
    {value: '33.5', name: '兰桂坊'},
    // ...
  ],
  '澳门': [
    {value: '41.5', name: '澳门塔'},
    {value: '39', name: '威尼斯人度假区'},
    {value: '39', name: '伦敦人度假区'},
    {value: '38.5', name: '新毫影汇度假区'},
    {value: '38', name: '大三巴牌坊'},
    {value: '33.5', name: '澳门巴黎铁塔'},
    {value: '33.5', name: '大炮台'},
    {value: '33.5', name: '渔人码头'},
    {value: '32.5', name: '妈阁庙'},
    {value: '30.5', name: '永利皇宫'},
    {value: '30', name: '玫瑰圣母堂'},
    {value: '30', name: '氹仔'},
    {value: '34', name: '赌场'},
    // ...
  ],
};
var option = {
  backgroundColor: "transparent",
  title: {
    // text: "热门词汇",
    left: "center",
    bottom: "5%",
    color: "black",
    textStyle: {
      fontSize: 20,
    },
  },
  grid: {
    top: "20%",
    left: "5%",
    right: "5%",
    bottom: "15%",
    containLabel: true,
  },
  tooltip: {
    show: true,
    borderColor: '#fe9a8bb3',
    borderWidth: 1,
    padding: [10, 15, 10, 15],
    confine: true,
    backgroundColor: 'rgba(255, 255, 255, .9)',
    textStyle: {
      color: 'hotpink',
      lineHeight: 22,
    },
    extraCssText:
      'box-shadow: 0 4px 20px -4px rgba(199, 206, 215, .7);border-radius: 4px;',
    formatter: function (params) {
      return params.name;
    },
  },
  series: [
    {
      type: 'wordCloud',

      shape: 'pentagon',

      left: 'center',
      top: 'center',
      width: '100%',
      height: '100%',
      right: null,
      bottom: null,

      sizeRange: [14, 50],

      rotationRange: [0, 0],
      rotationStep: 0,

      gridSize: 25,

      drawOutOfBound: false,

      layoutAnimation: true,

      textStyle: {
        fontFamily: 'PingFangSC-Semibold',
        fontWeight: 600,
        color: function (params) {
          let colors = [
            '#cf3d26fe',
            '#d43d26ff',
            '#b63fb6f5',
            '#9f87ffff',
            '#9E87FFb3',
            '#7a5afaff',
            '#055af8ff',
            '#fe9a8bb3',
            '#fe9a8bff',
            '#064388',
            '#46869b',
          ];
          return colors[parseInt(Math.random() * 10)];
        },
      },
      emphasis: {
        focus: 'none',
      },

      data: list,
    },
  ],
};

myChart4.setOption(option);
